/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.Evolucionar;

/**
 *
 * @author Jesus
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        b_detener.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_in_frase = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        p_out_frase = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        p_log_evolucion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        b_inicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rb_suma = new javax.swing.JRadioButton();
        rb_presicion = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        t_inicial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_cruzes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_mutaciones = new javax.swing.JTextField();
        b_detener = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t_precision = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rb_manual = new javax.swing.JRadioButton();
        rb_automatico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo Genetico v.23");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        p_in_frase.setColumns(20);
        p_in_frase.setRows(5);
        p_in_frase.setToolTipText("Ingrese una frase");
        jScrollPane1.setViewportView(p_in_frase);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("Frase Evolucionada");

        p_out_frase.setEditable(false);
        p_out_frase.setBackground(new java.awt.Color(204, 204, 204));
        p_out_frase.setColumns(20);
        p_out_frase.setRows(5);
        jScrollPane2.setViewportView(p_out_frase);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Ingrese Frase");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Log de Evolucion"));

        p_log_evolucion.setEditable(false);
        p_log_evolucion.setColumns(20);
        p_log_evolucion.setRows(5);
        jScrollPane3.setViewportView(p_log_evolucion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configuracion"));

        b_inicio.setBackground(new java.awt.Color(0, 153, 51));
        b_inicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_inicio.setText("Iniciar");
        b_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_inicioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Funcion de Ajuste");

        buttonGroup1.add(rb_suma);
        rb_suma.setText("Suma ASCII");
        rb_suma.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_sumaStateChanged(evt);
            }
        });

        buttonGroup1.add(rb_presicion);
        rb_presicion.setSelected(true);
        rb_presicion.setText("Precision Caracter");
        rb_presicion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_presicionStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Poblacion Inicial");

        t_inicial.setText("1024");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No Cruzes");
        jLabel5.setToolTipText("");

        t_cruzes.setText("150");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("No Mutaciones");

        t_mutaciones.setText("200");

        b_detener.setBackground(new java.awt.Color(204, 0, 51));
        b_detener.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_detener.setText("Detener");
        b_detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_detenerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Precision (%)");

        t_precision.setText("95");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Modo de Ejecucion");
        jLabel8.setToolTipText("");

        buttonGroup2.add(rb_manual);
        rb_manual.setText("Manual");

        buttonGroup2.add(rb_automatico);
        rb_automatico.setSelected(true);
        rb_automatico.setText("Automatico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b_detener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(t_cruzes))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addComponent(t_mutaciones))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(t_precision))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(t_inicial))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rb_suma)
                                .addGap(18, 18, 18)
                                .addComponent(rb_presicion))
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rb_manual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rb_automatico, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_suma)
                    .addComponent(rb_presicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_cruzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_mutaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t_precision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_manual)
                    .addComponent(rb_automatico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(b_detener, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_inicioActionPerformed
        if (iniciado == false) {
            //Configuraciones antes de iniciar        
            p_log_evolucion.setText("");
            p_out_frase.setText("");
            b_detener.setVisible(true);
            habilitar(false);
            detener = false;

            try {
                //Obener parametros
                String frase = p_in_frase.getText();

                int funcion = 0;
                if (!rb_suma.isSelected()) {
                    funcion = 1;
                }

                int poblacion = Integer.parseInt(t_inicial.getText());
                int cruzes = Integer.parseInt(t_cruzes.getText());
                int mutaciones = Integer.parseInt(t_mutaciones.getText());
                int precision = Integer.parseInt(t_precision.getText());

                e = new Evolucionar(frase, funcion, poblacion, precision, cruzes, mutaciones);

                //Tipo de ejecucion
                if (rb_automatico.isSelected()) {
                    b_inicio.setEnabled(false);
                    new Thread(new Runnable() {

                        @Override
                        public void run() {
                            String inicio = e.getDatosIniciales();
                            p_log_evolucion.setText(inicio);

                            //Generaciones
                            while (detener == false && e.evolucionCompleta() == false) {
                                System.out.println("Generacion " + e.generacion);
                                String t1 = e.getGeneracion();
                                p_log_evolucion.setText(p_log_evolucion.getText() + t1);
                            }

                            //Al terminar de generar
                            System.out.println("Sol: " + e.getSolucionFinal());
                            p_out_frase.setText(e.getSolucionFinal());
                            b_inicio.setEnabled(true);
                            b_detener.setVisible(false);
                            JOptionPane.showMessageDialog(contexto(), "La evolucion se ha completado :D", "Evolucion Completa", JOptionPane.INFORMATION_MESSAGE);                            
                            habilitar(true);
                            detener = true;
                            
                        }
                    }).start();
                } else {
                    iniciado = true;
                    String inicio = e.getDatosIniciales();
                    p_log_evolucion.setText(inicio);                    
                    b_inicio.setText("Siguiente Generacion");
                }

            } catch (Exception ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Problema", JOptionPane.INFORMATION_MESSAGE);

                habilitar(true);
                b_detener.setVisible(false);
            }
        } else {
            if (e.evolucionCompleta()) {
                System.out.println("Sol: " + e.getSolucionFinal());
                p_out_frase.setText(e.getSolucionFinal());
                b_detener.setVisible(false);                
                b_inicio.setText("Iniciar");
                JOptionPane.showMessageDialog(contexto(), "La evolucion se ha completado :D", "Evolucion Completa", JOptionPane.INFORMATION_MESSAGE);                
                habilitar(true);
                iniciado = false;

            } else {
                System.out.println("Generacion " + e.generacion);
                String t1 = e.getGeneracion();
                p_log_evolucion.setText(p_log_evolucion.getText() + t1);
            }
        }
    }//GEN-LAST:event_b_inicioActionPerformed

    private void b_detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_detenerActionPerformed
        detener = true;
        if(iniciado = true){
            iniciado = false;
            habilitar(true);
            b_inicio.setText("Iniciar");
            b_detener.setVisible(false);
        }
    }//GEN-LAST:event_b_detenerActionPerformed

    private void rb_presicionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_presicionStateChanged
        if (rb_presicion.isSelected()) {
            t_precision.setEnabled(true);
        }
    }//GEN-LAST:event_rb_presicionStateChanged

    private void rb_sumaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_sumaStateChanged
        if (rb_suma.isSelected()) {
            t_precision.setEnabled(false);
        }
    }//GEN-LAST:event_rb_sumaStateChanged

    private void habilitar(boolean valor) {
        rb_suma.setEnabled(valor);
        rb_presicion.setEnabled(valor);
        t_inicial.setEnabled(valor);
        t_cruzes.setEnabled(valor);
        t_mutaciones.setEnabled(valor);
        t_precision.setEnabled(valor);
        rb_manual.setEnabled(valor);
        rb_automatico.setEnabled(valor);

        if (valor == true) {
            if (rb_suma.isSelected()) {
                t_precision.setEnabled(false);
            } else {
                t_precision.setEnabled(true);
            }
        }
    }

    private JFrame contexto() {
        return this;
    }

    private boolean detener = false;
    private boolean iniciado = false;
    private Evolucionar e;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_detener;
    private javax.swing.JButton b_inicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea p_in_frase;
    private javax.swing.JTextArea p_log_evolucion;
    private javax.swing.JTextArea p_out_frase;
    private javax.swing.JRadioButton rb_automatico;
    private javax.swing.JRadioButton rb_manual;
    private javax.swing.JRadioButton rb_presicion;
    private javax.swing.JRadioButton rb_suma;
    private javax.swing.JTextField t_cruzes;
    private javax.swing.JTextField t_inicial;
    private javax.swing.JTextField t_mutaciones;
    private javax.swing.JTextField t_precision;
    // End of variables declaration//GEN-END:variables
}
